name: connect_four
description: "A new Flutter project."
publish_to: "none" 
version: 3.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flame: ^1.34.0
  flame_svg: ^1.11.18
  google_generative_ai: ^0.4.7
  flutter_dotenv: ^6.0.0
  http: ^1.6.0
  svg_flutter: ^0.0.1
  smooth_page_indicator: ^2.0.1
  confetti: ^0.8.0
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  path_provider: ^2.1.5
  audioplayers: ^5.2.1
  vibration: ^3.1.5
  flutter_local_notifications: ^20.0.0
  app_settings: ^7.0.0
  provider: ^6.1.5+1
  equatable: ^2.0.8
  google_mobile_ads: ^6.0.0
  timezone: ^0.10.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.8
  flutter_native_splash: ^2.4.7

# BU KISIMDA SADECE SPLASH AYARLARI OLMALI
flutter_native_splash:
  color: "#6a3de9"
  image: assets/image/icon.png
  ios: true
  android: true

# BURADAN SONRASI NORMAL DEVAM EDER
flutter:
  uses-material-design: true
  config:
    enable-swift-package-manager: false
  assets:
    - assets/image/
    - assets/fonts/
    - assets/wav/
    - assets/lang/
  fonts:
    - family: RubikSpray
      fonts:
        - asset: assets/fonts/RubikSprayPaint-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic

    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Bold.ttf
    - family: Orbitron
      fonts:
        - asset: assets/fonts/Orbitron-Medium.ttf
